# Generated by Django 5.2.6 on 2025-09-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('price', models.CharField(verbose_name=100000000000)),
                ('code', models.CharField(max_length=4)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
