# Generated by Django 5.2.6 on 2025-09-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_model',
            name='price',
            field=models.CharField(max_length=100000000000),
        ),
    ]
